export const taglinePhrases = [
  "IN EVERY BEGINNING DWELLS A MAGIC.",
  "RECURSIVE DESIGN",
  "PROCESS ZONE",
  "TINKERBELL WAS AN ENGINEER.",
  "FORM FOLLOWS PHOTOSYNTHESIS.",
  "TRUTH EMERGES THROUGH CONVERSATION, NOT THROUGH MONOLOGUE.",
  "IMAGINATION IS THE ONLY WEAPON IN THE WAR AGAINST REALITY.",
  "CHAOS IS JUST PATTERN UNREAD.",
  "PIXIE DUST ≈ QUANTUM NOISE.",
  "IS IT ALIVE OR JUST NEW?",
];
